version: "3.8"

services:
  weather-api:
    build: ./weather-api
    container_name: weather-api
    ports:
      - "5001:5000"
    networks:
      - backend

  geolocation-api:
    build: ./geolocation-api
    container_name: geolocation-api
    ports:
      - "5002:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
